CREATE TABLE projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    created TIMESTAMPTZ DEFAULT now() NOT NULL,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    description TEXT,
    materials TEXT,
    steps TEXT,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
);